version: '3.8'

services:

  web:
    build: .
    image: web
    container_name: map_web
    ports:
      - 5000:5000
    command: python3 manage.py run -h 0.0.0.0
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=server.config.DevelopmentConfig
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      - redis

  worker:
    image: web
    container_name: map_worker
    command: celery --app server.tasks.celery worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=server.config.DevelopmentConfig
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      - web
      - redis

  dashboard:
    image: web
    container_name: map_dashboard
    command: celery --app server.tasks.celery flower --port=5555 --broker=redis://redis:6379/0
    volumes:
      - .:/usr/src/app
    ports:
      - 5555:5555
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=server.config.DevelopmentConfig
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      - web
      - redis
      - worker

  redis:
    image: redis:6-alpine
    container_name: map_redis
